version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: astrawellick/devops-intro:latest
      - docker/push:
          image: astrawellick/devops-intro:latest

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - circleci-project-setup  # release branch

      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - circleci-project-setup

      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - circleci-project-setup
